### ISSUE TITLE
Summon Client Error

### ISSUE THREAD

**Issue by rodydavis** [SpinlockLabs/tesla.dart#8]
Summon Error: WebSocketException: Connection to 'https://streaming.vn.teslamotors.com:0/connect/111682172#' was not upgraded to websocket

**Comment by kendfinger** [comment]
I believe they have changed the Summon Client API and I will need to work on this to support it.

**Comment by rodydavis** [comment]
Actually I found out it could be a simulator error. I got it to show on a real device, but I will test soon with sending the SummonRequestMessages.

Do you have an example of how to use the summon client?

**Comment by kendfinger** [comment]
Sorry for the late reply, I just added some stuff to the Summon API.

See the bin/summon.dart file for an example. It's essentially a convenience wrapper around the WebSocket portion of the API.
